## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 1

# Need sudo for nooping
sudo: required

script:
    - julia --color=yes -e "using Pkg; Pkg.build()"
    # Julia gets installed in ~/julia
    - sudo ~/julia/bin/julia --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(coverage=true);"

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl


# Deploy Documentation
jobs:
  include:
    - stage: Documentation
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip

