## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.5
  - nightly
notifications:
  email: false
git:
  depth: 1

script:
    - julia --color=yes -e "using Pkg; Pkg.build()"
    - julia --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(coverage=true);"

after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("SystemSnoop")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'


# Deploy Documentation
jobs:
  include:
    - stage: Documentation
      julia: 1.2
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip

