name = "MemSnoop"
uuid = "c30797a9-91c2-5451-bcc7-95710ac2a28d"
authors = ["Mark Hildebrand <mhildebrand@ucdavis.edu>"]
version = "0.1.0"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[targets]
test = ["Test", "Combinatorics"]
